import { MockData, Movie, Series, SpecialProgram } from "@/type/content";

export const mockMovies: Movie[] = [
    {
        id: 1,
        title: "Nada a Perder",
        slug: "nada-a-perder",
        image: "/images/nada-a-perder.jpg",
        bannerImage: "/images/nada-a-perder-banner.jpg",
        description: "A história de Edir Macedo, fundador da Igreja Universal do Reino de Deus",
        synopsis: "Baseado no livro autobiográfico de Edir Macedo, o filme conta a trajetória de fé e determinação do fundador da Igreja Universal do Reino de Deus.",
        ageRating: "12",
        duration: "2h 10min",
        durationMinutes: 130,
        genre: ["Drama", "Biografia"],
        year: 2018,
        category: 'movie',
        featured: true,
        reviews: { average: 8.5, total: 1245 },
        tags: ["biografia", "fé", "superação", "brasil"],
        releaseDate: "2018-08-30",
        trailer: "/videos/nada-a-perder-trailer.mp4",
        available: true,
        videoUrl: "/videos/nada-a-perder-full.mp4",
        director: "Alexandre Avancini",
        cast: ["Petrônio Gontijo", "Day Mesquita", "Beth Goulart"]
    },
    {
        id: 2,
        title: "Nada a Perder 2",
        slug: "nada-a-perder-2",
        image: "/images/nada-a-perder-2.jpg",
        bannerImage: "/images/nada-a-perder-2-banner.jpg",
        description: "A continuação da história de Edir Macedo",
        synopsis: "O segundo filme da trilogia mostra os desafios enfrentados por Edir Macedo na consolidação da Igreja Universal.",
        ageRating: "12",
        duration: "1h 58min",
        durationMinutes: 118,
        genre: ["Drama", "Biografia"],
        year: 2019,
        category: 'movie',
        featured: true,
        reviews: { average: 8.2, total: 987 },
        tags: ["biografia", "fé", "perseverança", "brasil"],
        releaseDate: "2019-05-23",
        trailer: "/videos/nada-a-perder-2-trailer.mp4",
        available: true,
        videoUrl: "/videos/nada-a-perder-2-full.mp4",
        director: "Alexandre Avancini",
        cast: ["Petrônio Gontijo", "Day Mesquita", "Beth Goulart"]
    },
    {
        id: 3,
        title: "O Rico e Lázaro",
        slug: "o-rico-e-lazaro-filme",
        image: "/images/rico-lazaro-filme.jpg",
        bannerImage: "/images/rico-lazaro-filme-banner.jpg",
        description: "A adaptação cinematográfica da novela bíblica",
        synopsis: "Baseado na parábola bíblica, conta a história de dois homens com destinos opostos: um rico e um mendigo.",
        ageRating: "L",
        duration: "2h 15min",
        durationMinutes: 135,
        genre: ["Drama", "Religioso"],
        year: 2020,
        category: 'movie',
        featured: false,
        reviews: { average: 7.8, total: 654 },
        tags: ["bíblico", "parábola", "drama", "fé"],
        releaseDate: "2020-12-25",
        trailer: "/videos/rico-lazaro-filme-trailer.mp4",
        available: true,
        videoUrl: "/videos/rico-lazaro-filme-full.mp4",
        director: "Marcelo Travesso",
        cast: ["Igor Rickli", "Tatá Werneck", "Caio Castro"]
    }
];

export const mockSeries: Series[] = [
    {
        id: 101,
        title: "A Terra Prometida",
        slug: "a-terra-prometida",
        image: "/images/terra-prometida.jpg",
        bannerImage: "/images/terra-prometida-banner.jpg",
        description: "A saga épica do povo hebreu em busca da Terra Prometida",
        synopsis: "Acompanhe a jornada de Moisés e os filhos de Israel desde o Egito até a Terra Prometida, numa produção épica que retrata os grandes milagres e desafios do povo de Deus.",
        ageRating: "10",
        duration: "45min por episódio",
        durationMinutes: 45,
        genre: ["Drama", "Religioso", "História"],
        year: 2016,
        category: 'series',
        featured: true,
        reviews: { average: 9.1, total: 3456 },
        tags: ["bíblico", "moisés", "milagres", "história"],
        releaseDate: "2016-01-18",
        trailer: "/videos/terra-prometida-trailer.mp4",
        available: true,
        videoUrl: "/videos/terra-prometida-s01e01.mp4",
        seasons: 2,
        episodes: 176,
        status: "Finished",
        creator: "Cristiane Cardoso",
        cast: ["Guilherme Winter", "Sergio Marone", "Giselle Itié"],
        nextEpisode: undefined
    },
    {
        id: 102,
        title: "O Rico e Lázaro",
        slug: "o-rico-e-lazaro",
        image: "/images/rico-lazaro.jpg",
        bannerImage: "/images/rico-lazaro-banner.jpg",
        description: "A novela bíblica que conquistou o Brasil",
        synopsis: "Uma superprodução que retrata a vida no tempo de Jesus, contando histórias de fé, amor e redenção através dos personagens Asher e Lázaro.",
        ageRating: "L",
        duration: "50min por episódio",
        durationMinutes: 50,
        genre: ["Drama", "Religioso", "Romance"],
        year: 2017,
        category: 'series',
        featured: true,
        reviews: { average: 8.7, total: 2789 },
        tags: ["bíblico", "jesus", "amor", "redenção"],
        releaseDate: "2017-03-27",
        trailer: "/videos/rico-lazaro-trailer.mp4",
        available: true,
        videoUrl: "/videos/rico-lazaro-s01e01.mp4",
        seasons: 1,
        episodes: 334,
        status: "Finished",
        creator: "Cristiane Cardoso",
        cast: ["Igor Rickli", "Tatá Werneck", "Caio Castro"],
        nextEpisode: undefined
    },
    {
        id: 103,
        title: "Jesus",
        slug: "jesus-serie",
        image: "/images/jesus-serie.jpg",
        bannerImage: "/images/jesus-serie-banner.jpg",
        description: "A vida e os ensinamentos de Jesus Cristo",
        synopsis: "Uma produção que retrata a vida de Jesus Cristo, desde seu nascimento até sua ressurreição, mostrando seus milagres, ensinamentos e o amor incondicional.",
        ageRating: "L",
        duration: "45min por episódio",
        durationMinutes: 45,
        genre: ["Drama", "Religioso", "História"],
        year: 2018,
        category: 'series',
        featured: true,
        reviews: { average: 9.3, total: 4567 },
        tags: ["jesus", "milagres", "ensinamentos", "salvação"],
        releaseDate: "2018-07-19",
        trailer: "/videos/jesus-serie-trailer.mp4",
        available: true,
        videoUrl: "/videos/jesus-serie-s01e01.mp4",
        seasons: 1,
        episodes: 194,
        status: "Finished",
        creator: "Cristiane Cardoso",
        cast: ["Dudu Azevedo", "Nanda Costa", "Petrônio Gontijo"]
    }
];

export const mockSpecialPrograms: SpecialProgram[] = [
    {
        id: 201,
        title: "Escola da Fé",
        slug: "escola-da-fe",
        image: "/images/escola-da-fe.jpg",
        bannerImage: "/images/escola-da-fe-banner.jpg",
        description: "Programa de ensino bíblico com Edir Macedo",
        synopsis: "Um programa educativo que ensina os princípios fundamentais da fé cristã, com explicações práticas e aplicáveis ao dia a dia.",
        ageRating: "L",
        duration: "30min",
        durationMinutes: 30,
        genre: ["Educativo", "Religioso"],
        year: 2023,
        category: 'program',
        featured: true,
        reviews: { average: 9.5, total: 2345 },
        tags: ["ensino", "fé", "bíblia", "educação"],
        releaseDate: "2023-01-15",
        available: true,
        videoUrl: "/videos/escola-da-fe-latest.mp4",
        type: "Programa de Ensino",
        schedule: "Domingo às 10h",
        nextBroadcast: "2024-01-28T10:00:00Z"
    },
    {
        id: 203,
        title: "Despertar da Fé",
        slug: "despertar-da-fe",
        image: "/images/despertar-da-fe.jpg",
        bannerImage: "/images/despertar-da-fe-banner.jpg",
        description: "Programa matinal de oração e reflexão",
        synopsis: "Comece seu dia com palavras de fé e esperança. Um programa que traz reflexões bíblicas para fortalecer sua caminhada espiritual.",
        ageRating: "L",
        duration: "45min",
        durationMinutes: 45,
        genre: ["Devocional", "Religioso"],
        year: 2023,
        category: 'program',
        featured: false,
        reviews: { average: 9.2, total: 3421 },
        tags: ["oração", "reflexão", "devocional", "manhã"],
        releaseDate: "2023-02-01",
        available: true,
        videoUrl: "/videos/despertar-da-fe-latest.mp4",
        type: "Programa Devocional",
        schedule: "Segunda a Sexta às 6h",
        nextBroadcast: "2024-01-29T06:00:00Z"
    }
];

export const mockData: MockData = {
    movies: mockMovies,
    series: mockSeries,
    specialPrograms: mockSpecialPrograms
};

export const categories = {
    main: ['movie', 'series', 'program'],
    genres: ['Drama', 'Religioso', 'História', 'Biografia', 'Romance', 'Educativo', 'Talk Show', 'Testemunho', 'Devocional'],
    ageRatings: ['L', '10', '12', '14', '16', '18']
};